language: php
os: linux
dist: bionic
if: tag IS blank

jobs:
  include:
    - php: '7.1'
      env: SYMFONY_VERSION="3.4.*"
    - php: '7.4'
      env: SYMFONY_VERSION="3.4.*"
    - php: '7.2'
      env: SYMFONY_VERSION="4.4.*"
    - php: '7.4'
      env: SYMFONY_VERSION="4.4.*"

before_install:
  - composer global require hirak/prestissimo
  - composer config extra.symfony.require "${SYMFONY_VERSION}"
  - composer config extra.symfony.allow-contrib true

install:
  - composer require symfony/flex --no-update # adds flex, suppress composer.lock
  - composer update symfony/*                 # updates to SYMFONY_VERSION, but runs recipes
  - git reset --hard                          # reset tracked files
  - git clean -df                             # clean up recipe generated files and folders

script:
  - composer run-script quality

after_success:
  - travis_retry php vendor/bin/php-coveralls
